# Site settings
title: Edoardo Spadoni
description: 'Software Engineer and Linux Enthusiast'
url: 'https://edospadoni.github.io'
baseurl: '/'

author:
  name: 'Edoardo Spadoni'
  github_username:  edospadoni
  linkedin_username:  edospadoni
  twitter_username: edospadoni

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
